### ISSUE TITLE
Cinema Database

### ISSUE THREAD

**Issue by at-khanhnguyen** [AT-PHPIntership/booking-ticket#2]
## Database: 
Nhờ anh chị xem giúp em cái database với ạ: 
### Updated 1: 
![cinema-database3](https://user-images.githubusercontent.com/40163404/43071398-e69b68d2-8e9c-11e8-82a5-e69d45962719.png)
### Update 2: 
![image](https://user-images.githubusercontent.com/40163404/43178711-e3eb8966-8ff8-11e8-8798-29025e92c60a.png)
### Update 3: 
![image](https://user-images.githubusercontent.com/40163404/43236262-438f6148-90ae-11e8-8099-60cfd3c51142.png)
### Final:
![image](https://user-images.githubusercontent.com/40163404/43245510-bf496b1a-90d8-11e8-965c-b7be9b6cfa6f.png)

**Comment by at-huenguyen** [comment]
- chị nghĩ ko cần bảng `ticket` vì cứ theo `schedule` vs `seat` của 1 `room` là đc. Nên bỏ bảng `ticket` vs `detail_booking`.
- ko thấy bọn em cho chọn ghế.
- trong bảng `film` cũng nên có cột `rating` cho phim nữa.
- bảng `schedules` nên liên kết vs bảng `seats` thay vì `room` chứ hè?

**Comment by at-khanhnguyen** [comment]
@at-huenguyen  em sửa lại như này được không chị.

**Comment by at-huenguyen** [comment]
@at-khanhnguyen

**Comment by at-huenguyen** [comment]
@at-khanhnguyen

**Comment by at-huenguyen** [comment]
Khánh, em xem lại chỗ này tí nha:

**Comment by at-khanhnguyen** [comment]
Update lần 3 nhờ chị @at-huenguyen xem giúp em với ạ.

**Comment by at-huenguyen** [comment]
@at-khanhnguyen

**Comment by at-huenguyen** [comment]
@at-khanhnguyen 
Ổn hơn rồi đó em.
Mà chỗ `seats` vs `booking_detail` quan hệ `1 - nhiều` nha em
